### ISSUE TITLE
Web interface (Mainsail/Fluidd), M73, Slicer issues

### ISSUE THREAD

**Issue by joelpr1234** [utkabobr/DuckPro-Kobra3#13]
Thanks for this firmware. In my first attempt, it fail, I had to do the emergency recovery, but I got it working.

In the first point of the readme is this:

"Features (Simple)
Web interface (Mainsail/Fluidd)"

How can I access Fluidd? Or, can I install it? 

To be honest, I'm very new with 3D printing, I have the Flashforge 5M Pro and a few days ago installed Klipper Mod to it, it has Mainsail and Fluidd in separate ports, it has webcam access and many more. I'm still confused of many names, Marlin, Klipper, Mainsail, Fluidd, Orca and others.

Assuming the limitation is GoKlipper, but I believe the Kobra 3 has better hardware(CPU) than the AD5M Pro. 

I'm also receiving M73 unknown commands, how I get rid of them? 

Another thing is, I try to print using Anycubic Slicer Next, which is based on Orca Slicer, and I get the file uploaded to the printer but it freezes in the processing, Orca Slicer works fine uploading. If I go to the printer, select print, select the file uploaded by AS Next, I receive a message "device lacks automatic leveling. do it before printing." I still like to use AS Next because the camera works, but I like the Mainsail web server, I like more Fluidd, but better Mainsail than nothing.

I have the ACE Pro, soon I'm receiving a second for 8 colors, I usually print one color at a time, but printing multiple colors in one print, anything that I should know?

Thank you again.

**Comment by weekendkoder** [comment]
My guess is, it needs to be installed. Not sure if fluidd works (should be the same as MainSail). If it is not shipped in another release, you could try to rePack the CFW with fluidd, instead of MainSail (or keep both). I am not familiar with Klipper / GoKlipper. Just an assumption.
