### ISSUE TITLE
Ship strace

### ISSUE THREAD

**Issue by Jookia** [utkabobr/DuckPro-Kobra3#15]
Hi there! It would be really cool if you shipped strace too. We've been using this for reversing the ACE so it's a very useful tool.

**Comment by systemik** [comment]
Pick it from here : https://github.com/systemik/Kobra3-Firmware/blob/main/update-preparation/cfw/binaries/strace
Then copy to the printer. Do a chmod +x to allow execution

**Comment by Jookia** [comment]
Oh cool! You can close this. :)
