### ISSUE TITLE
Removal of DuckPro

### ISSUE THREAD

**Issue by nolantern** [utkabobr/DuckPro-Kobra3#25]
Hey how do I remove everything in case of a warrity case ?

**Comment by utkabobr** [comment]
Remove:
/useremain/dist
/useremain/home/ytka/

Then install stock .swu file, should be fine

**Comment by utkabobr** [comment]
Please note that /useremain/home/ytka/printer_data/config/anycubic_config is linked to the anycubic's services. Do not delete anything inside it, unmount it via umount first

**Comment by nolantern** [comment]
Fortunately, I was able to solve my problem without sending in the device. I have not tested your solution but it answers the question.

Thank you for your answer and for this awesome upgrade for my Kobra 3!
