### ISSUE TITLE
Can´t install the update.

### ISSUE THREAD

**Issue by Spidywert** [utkabobr/DuckPro-Kobra3#3]
Hello,

I have a few issues, first of all i must rename the Folder also to Update on the latest Firmware (2.3.3.9) it didn´t update the Software on the fly.

And a secont one are a Message of that the Local Storage are insufficante and i have to remove some files, but the Storage was allredy empty.

Thanks for that Work.

**Comment by utkabobr** [comment]
So it doesn't react at all if you don't rename a folder and just boot with it?
Newer versions of anycubic's firmware should try to install it automatically, once install is started you should hear "At the doom's gate" tune.
Do not reboot printer at least 15-20 minutes to ensure everything is installed properly.

Local storage might mean internal memory of the motherboard, please check how many space does your gcodes consume.

**Comment by Spidywert** [comment]
after doing the other firmware i got the a reaction. and a while there was a connection to klipper. but i will try it again.
 I have deletet all the unnecessery files from the local storage.

**Comment by Spidywert** [comment]
soo, i have it working. try it to stick the usb stick after the rebooting and waitet for je music. it seems like it was my fault 👯. thank you for Help

**Comment by utkabobr** [comment]
Closing as a successfull installation
