### ISSUE TITLE
Time and date reset to 1970

### ISSUE THREAD

**Issue by Bespinuk** [utkabobr/DuckPro-Kobra3#64]
Hi all the time and date on my printer seem to keep resetting to 1970 and are not upto date with the network. Any ideas?

**Comment by utkabobr** [comment]
It's to be expected. It wasn't required for stock firmware to work, so anycubic haven't configured time sync

**Comment by Bespinuk** [comment]
Thanks seems a bit odd as most things that access the Internet tend to sync up the time date.

**Comment by Bespinuk** [comment]
re flashed the firmware back to the stock and then back again and it appears to be the right day and time again.
